services:
  airflow-webserver:
    image: apache/airflow:2.6.2-python3.12
    container_name: airflow-webserver
    build:
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    env_file:
      - .env
    volumes:
      - ./dags:/opt/airflow/dags
      - ./logs:/opt/airflow/logs
      - ./plugins:/opt/airflow/plugins
    command:
      - /bin/bash
      - -c
      - >
        airflow db init &&
        airflow users create --username admin --password admin --firstname Admin --lastname Admin --role Admin --email admin@example.com &&
        airflow webserver

  airflow-scheduler:
    image: apache/airflow:2.6.2-python3.12
    container_name: airflow-scheduler
    build:
      dockerfile: Dockerfile
    volumes:
      - ./dags:/opt/airflow/dags
      - ./logs:/opt/airflow/logs
      - ./plugins:/opt/airflow/plugins
    command:
      - /bin/bash
      - -c
      - >
        airflow db migrate &&
        airflow scheduler
  