name: CI/CD Pipeline for project

on:
  push:
    branches:
      - main

jobs:
  run_script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.12.0"

      - name: "Create env file"
        run: |
          touch .env
          echo API_ENDPOINT="https://xxx.execute-api.us-west-2.amazonaws.com" >> .env
          echo KAGGLE_KEY=${{ secrets.KAGGLE_KEY }} >> .env
          echo KAGGLE_USERNAME=${{ secrets.KAGGLE_USERNAME }} >> .env
          echo SHEETS_KEY=${{ secrets.SHEETS_KEY }} >> .env
          echo SHEET_ID=${{ secrets.SHEET_ID }} >> .env
          cat .env

      - name: Set up airflow
        run: docker compose up --build

      - name: Set up API
        run: docker pull jaroslawgawrych/loan_approval_api:latest
          docker run -d -p 5000:5000 jaroslawgawrych/loan_approval_api:latest

      - name: Test model
        run: python /models/client.py

      - name: Upload log artifact
        uses: actions/upload-artifact@v4
        with:
          name: log
          path: log.txt
